import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";

const jetbrainsMono = JetBrains_Mono({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
    variable: "--font-jetbrainsMono",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${jetbrainsMono.variable} bg-slate-900`}>
            <body
                className={`${jetbrainsMono.className} antialiased bg-slate-900 text-white min-h-screen`}
            >
                <Header />
                <StairTransition/>
                <PageTransition>{children}</PageTransition>
            </body>
        </html>
    );
}
